//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string KeyWord { get; set; }
        public string Image { get; set; }
        public int ParentID { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string MetaDescription { get; set; }
        public string Description { get; set; }
    }
}
